[toolchain]
anchor_version = "0.32.0"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
prediction_market = "D254EggCVsZ7jKtJJ29diEv3P4qqjn5APBAvcRwDNsyE"

[programs.devnet]
prediction_market = "D254EggCVsZ7jKtJJ29diEv3P4qqjn5APBAvcRwDNsyE"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json tests/**/*.ts --timeout 60000"
